### ISSUE TITLE
In need of user information from api

### ISSUE THREAD

**Issue by Medic1111** [chingu-voyages/v40-bears-team-29#35]
I need the user's information to be sent with the response at login and register. I suggest on tomorrow's meeting we structure data model to minimize the chance having to revisit this in the future =)

**Comment by Roupiye** [comment]
fixed in #36

**Comment by Medic1111** [comment]
Hey, can you check a request from our client? Getting sql error at sign up

**Comment by Roupiye** [comment]
its working fine for me, try running `npx sequelize-cli db:drop` `npx sequelize-cli db:create` `npx sequelize-cli db:migrate`, i changed the user name field on the pr so you have to sync it in your local machine
