### ISSUE TITLE
BUG: if you go to /users/user1 using the url when logged you are "redirected" to login

### ISSUE THREAD

**Issue by Roupiye** [chingu-voyages/v40-bears-team-29#70]
current behaviour: you log in, you go to your user profile, you press f5, and get redirected to login

expected behaviour: you login in, you go to your user profile, you press f5, and you get the user profile page

**Comment by TopRoupi** [comment]
lol never mind. basically the posts created using seed are set to the same created_at value, so when ordering using created_at you have a bunch of posts with same value and they are ordered at random, in production this is impossible to happen. not really a bug in the sequelize but in the way it sets the created_at when bulk inserting.
